services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/catalog/Catalog.API/Dockerfile
    ports:
     - "8010:8000"
    depends_on:
     - catalogdb
    environment:
      - ASPNETCORE_URLS=http://+:8000
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
      - CatalogSettings__DatabaseName=CatalogDb
      - CatalogSettings__TypesCollection=Types
      - CatalogSettings__BrandsCollection=Brands
      - CatalogSettings__ProductsCollection=Products
  catalogdb:
    image: mongo
    container_name: catalogdb
    ports:
    - "27017:27017"
    volumes:
    - catalogdata:/data/db
volumes:
  catalogdata:
